In [1]:
import tensorflow as tf

In [2]:
input_n=3
layer_1=4

weit=tf.Variable(tf.random_normal([input_n,layer_1]))



In [3]:
init_variable = tf.initialize_all_variables()

In [4]:
with tf.Session() as sess:
    sess.run(init_variable)
    print sess.run(weit)

[[-0.19367924  0.22547026 -0.85668975 -1.49684787]
 [ 0.1701465   1.02241421  1.45955372  1.27105021]
 [ 2.03065443  0.66138834 -0.57610184  1.2783922 ]]


In [5]:
import numpy as np

In [7]:
s= np.ndarray([3,4])

In [8]:
print(s[])

[[  0.00000000e+000   4.94065646e-324   9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323   2.96439388e-323   3.45845952e-323]
 [  3.95252517e-323   4.44659081e-323   4.94065646e-323   5.43472210e-323]]


In [17]:
print(s[:,0:2])

[[  0.00000000e+000   4.94065646e-324]
 [  1.97626258e-323   2.47032823e-323]
 [  3.95252517e-323   4.44659081e-323]]


In [1]:
from gensim.models import Word2Vec

ImportError: No module named gensim.models