In [9]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [6]:
wordVec = DataFrame([
        ("Hi I heard about Spark".split(" "), ),
        ("I wish Java could use case classes".split(" "), ),
        ("Logistic regression models are neat".split(" "), )
    ], columns=["text"])

In [7]:
print(wordVec)

                                         text
0                [Hi, I, heard, about, Spark]
1  [I, wish, Java, could, use, case, classes]
2   [Logistic, regression, models, are, neat]


In [8]:
wordVec.shape

(3, 1)

In [13]:
multiDim= np.ndarray((2,3,2,3))
multiDim

array([[[[  9.71897907e-312,   8.03843612e-315,   8.03843438e-315],
         [  8.03843470e-315,   9.71897902e-312,   8.03843470e-315]],

        [[  8.03843470e-315,   8.03845146e-315,   8.03845272e-315],
         [  8.03845130e-315,   8.03843422e-315,   8.03843422e-315]],

        [[  8.03843422e-315,   9.71897907e-312,   8.03845146e-315],
         [  9.71897907e-312,   8.03845272e-315,   9.71897907e-312]]],


       [[[  8.03845130e-315,   9.71897908e-312,   8.03843501e-315],
         [  8.03843422e-315,   9.71897902e-312,   9.71897906e-312]],

        [[  9.71897906e-312,   9.71897906e-312,   9.71897909e-312],
         [  9.71897906e-312,   9.71921566e-312,   0.00000000e+000]],

        [[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
         [  0.00000000e+000,   4.94065646e-324,   9.71928833e-312]]]])

In [14]:
positive_labels = [[0, 1] for _ in range(10)]
negative_labels = [[1, 0] for _ in range(10)]
y = np.concatenate([positive_labels, negative_labels], 0)


array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

In [38]:
np.random.seed(3)
np.random.permutation(np.arange(len(y)))

array([14,  2,  1, 17,  4, 16,  6,  7, 15, 12,  9, 11, 19, 18, 13,  5,  0,
        8,  3, 10])

In [36]:
np.random.permutation(np.arange(len(y)))

array([17, 11,  2,  9, 12,  6,  0,  8,  3,  4, 10, 19, 13, 18, 15, 16,  1,
       14,  5,  7])