In [1]:
import numpy as np
from numpy import ndarray, random
import math

In [171]:
li=np.array(range(5))
li

array([0, 1, 2, 3, 4])

In [172]:
li[0:-1]

array([0, 1, 2, 3])

In [173]:
t=zip(li[0:-1],li[1:])

In [174]:
[x[0] for x in t]

[0, 1, 2, 3]

In [183]:
inputdata=np.array([10,100,100,9])

In [59]:
inputNum=3
nerualNum=4
loc=0
scale=0.1
weight_matrix = random.normal(loc=loc, scale=scale, size=inputNum * nerualNum).reshape((nerualNum, inputNum))
bias_vector = random.normal(loc=loc, scale=scale, size=nerualNum)
active_vector = ndarray((nerualNum,), dtype=float, offset=0)
c = ndarray((nerualNum,), dtype=float, offset=0)

print(weight_matrix,bias_vector,active_vector,active_vector,sep='\n')

[[ 0.17963795  0.12087337 -0.05804802]
 [-0.08405666  0.04034077  0.02232976]
 [ 0.00557541 -0.01567281  0.08404401]
 [-0.08700755 -0.11917005  0.08110591]]
[ 0.05329366  0.1034338   0.21007733 -0.13959594]
[  1.22244617e-311   1.22241236e-311   1.22244578e-311   1.22244616e-311]
[  1.22244617e-311   1.22241236e-311   1.22244578e-311   1.22244616e-311]


In [181]:
weight_matrix

array([[-0.0362808 ,  0.04485677, -0.14607731],
       [-0.18413328, -0.03621946,  0.09909718],
       [ 0.0004091 , -0.04253765, -0.09365565],
       [-0.16176578, -0.06433605,  0.11774046]])

In [182]:
weight_matrix.shape

(4, 3)

In [185]:
inputdata.dot(weight_matrix)

array([-20.19111855,  -8.0061676 ,   0.14304487])

In [186]:
np.sum(inputdata*weight_matrix[:,0])

-20.191118547428911

In [78]:
#矩阵转置
weight_matrix.transpose()

array([[-0.11546964,  0.15484891,  0.05899302, -0.04779419],
       [ 0.01204226, -0.17518505, -0.02548814,  0.0527019 ],
       [-0.02660603,  0.14384632, -0.00299346, -0.21116459]])

In [64]:
# 一个向量乘以一个举证，不是矩阵的点积运算
inputdata*weight_matrix

array([[ -1.15469642,   1.20422622,  -2.66060279],
       [  1.54848912, -17.5185048 ,  14.38463192],
       [  0.58993016,  -2.54881362,  -0.29934627],
       [ -0.47794193,   5.27019   , -21.11645851]])

In [85]:
wb=inputdata*weight_matrix
wb

array([[ -1.15469642,   1.20422622,  -2.66060279],
       [  1.54848912, -17.5185048 ,  14.38463192],
       [  0.58993016,  -2.54881362,  -0.29934627],
       [ -0.47794193,   5.27019   , -21.11645851]])

In [90]:
# 按照行求和并加上偏移量
wb.sum(axis=1)+bias_vector

array([ -2.52851496,  -1.6162938 ,  -2.18939224, -16.28787961])

In [89]:
wb

array([[ -1.15469642,   1.20422622,  -2.66060279],
       [  1.54848912, -17.5185048 ,  14.38463192],
       [  0.58993016,  -2.54881362,  -0.29934627],
       [ -0.47794193,   5.27019   , -21.11645851]])

In [180]:
np.sum(weight_matrix[:,1]*np.array(range(4)))

-0.31430291701666546

沿着纵向求和

In [65]:
# 沿着纵向求和
weight_matrix.sum(axis=0)

array([ 0.05057809, -0.13592902, -0.09691776])

沿着横向求和

In [82]:
# 沿着横向求和
weight_matrix.sum(axis=1)

array([-0.13003341,  0.12351018,  0.03051142, -0.20625688])

In [69]:
sum([-0.11546964,  0.01204226, -0.02660603])

-0.13003341

In [74]:
bias_vector.transpose()

array([ 0.08255804, -0.03091004,  0.06883748,  0.03633082])

In [73]:
bias_vector

array([ 0.08255804, -0.03091004,  0.06883748,  0.03633082])

In [75]:
dl=[-0.04412604,-0.06581486]

神经元sigmoid函数，传入计算列表返回结果列表

In [65]:
sigmoid = lambda dataList: np.array([1 / (1 + np.exp(-x)) for x in dataList])

In [76]:
sigmoid(dl)

array([ 0.48897028,  0.48355222])

残差项计算

In [156]:
li=list(range(2,11))
li.reverse()
f=np.array(range(1,10))
y=np.array(li)
errorItem=lambda fList,yList:fList*(1-fList)*(fList-yList)

In [160]:
errorItem(f,y)

array([   0,   14,   30,   36,   20,  -30, -126, -280, -504])

In [168]:
errorItem(np.array([9]),np.array([2]))

array([-504])

In [58]:
(1-f)

NameError: name 'f' is not defined

In [166]:
(1-f)*f

array([  0,  -2,  -6, -12, -20, -30, -42, -56, -72])

In [162]:
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [163]:
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

矩阵构造

In [52]:
orli=np.array(range(6))
orli2=np.array(range(3))

In [28]:
orli

array([0, 1, 2, 3, 4, 5])

In [8]:
list(orli)*3

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [27]:
orMat=orli.repeat([3,6])

ValueError: operands could not be broadcast together with shape (6,) (2,)

In [18]:
orMat.reshape((3,6))

array([[0, 0, 0, 1, 1, 1],
       [2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5]])

In [47]:
orli.reshape([6,1]).repeat(3,axis=-1).T

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [54]:
orli2.reshape((3,1))*orli.reshape([6,1]).repeat(3,axis=-1).T

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10]])

In [56]:
orli2

array([0, 1, 2])

In [51]:
orli

array([0, 1, 2, 3, 4, 5])

In [57]:
orli2.size

3

In [60]:
np.abs(weight_matrix)

array([[ 0.17963795,  0.12087337,  0.05804802],
       [ 0.08405666,  0.04034077,  0.02232976],
       [ 0.00557541,  0.01567281,  0.08404401],
       [ 0.08700755,  0.11917005,  0.08110591]])

In [67]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [69]:
orli.shape

TypeError: 'tuple' object is not callable

In [74]:
0.5*(3-5)**2

2.0

In [86]:
f=np.array([0.48897027956688921, 0.48355222067998077])
e=np.array([0.14344337321810227])
w=np.array([[ 0.19218611,  0.10726759]])
print(1-f)
print((1-f)*f)
print(e.dot(w))

[ 0.51102972  0.51644778]
[ 0.24987835  0.24972947]
[ 0.02756782  0.01538682]


In [87]:
0.14344337321810227*0.19218611

0.027567823904065255